# General
spring.application.name=users
server.servlet.context-path=/users
server.port=8080

# H2 Database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.h2.Driver
spring.h2.console.enabled=true
spring.jpa.show-sql=true

# Spring Security
#spring.security.user.name=User
#spring.security.user.password=UserPassword